#!/usr/bin/python

# md - a simple maildir command line user agent
# Copyright (C) 2010  Nic Ferrier <nic@ferrier.me.uk>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""
md - A maildir command line user agent.
"""

__author__ = "Nic Ferrier <nic@ferrier.me.uk>"
__version__ = 0.1

import os.path
import os
import sys
from mdlib import *

## This should be redefined as an option and a thread local
## Default value should come from an env var or be ~/Maildir
HOMEMAILDIR = "~/Maildir"
MAILDIR = os.path.expanduser(os.environ.get("MAILDIR", HOMEMAILDIR))

# Depends on cmdlin
import cmdln

class MdCLI(cmdln.Cmdln):
    name = "md"

    def get_optparser(self):
        """Override to allow specification of the maildir"""
        p = cmdln.Cmdln.get_optparser(self)
        p.add_option(
            "-M",
            "--maildir",
            action="store",
            dest="maildir"
            )
        return p

    def do_lsfolders(self, subcmd, opts):
        """List the sub folders of the maildir"""
        maildir = getattr(self.options, "maildir",MAILDIR)
        client = MdClient(maildir)
        client.lsfolders(stream=sys.stdout)

    def do_ls(self, subcmd, opts, folder=""):
        """List messages in the specified folder"""
        maildir = getattr(self.options, "maildir",MAILDIR)
        client = MdClient(maildir)
        client.ls(foldername=folder,stream=sys.stdout)

    def do_lisp(self, subcmd, opts, folder=""):
        """List messages in the specified folder in JSON format"""
        maildir = getattr(self.options, "maildir",MAILDIR)
        client = MdClient(maildir)
        client.lisp(foldername=folder,stream=sys.stdout)

    def do_make(self, subcmd, opts, path):
        """Make a maildir at the specified path.

        If the path is relative then create under MAILDIR
        else create at the absolute location.
        """
        maildir = getattr(self.options, "maildir",MAILDIR)
        d = path[0] if path[0][0] == "/" else joinpath(maildir, path[0])
        os.makedirs(joinpath(d, "cur"))
        os.makedirs(joinpath(d, "new"))
        os.makedirs(joinpath(d, "tmp"))

    def do_rm(self, subcmd, opts, message):
        """Remove the specified message"""
        maildir = getattr(self.options, "maildir",MAILDIR)
        client = MdClient(maildir)
        client.remove(message)

    def do_text(self, subcmd, opts, message):
        """Get the best text part of the specified message"""
        maildir = getattr(self.options, "maildir",MAILDIR)
        client = MdClient(maildir)
        client.gettext(message, sys.stdout)

    def do_struct(self, subcmd, opts, message):
        """Get the structure of the specified message"""
        maildir = getattr(self.options, "maildir",MAILDIR)
        client = MdClient(maildir)
        client.getstruct(message, sys.stdout)

    def do_shell(self, subcmd, opts):
        """Run a shell for md.

        The MAILDIR cannot be set with this command except through the
        environment variable.
        """
        # TODO fix this because it's broken right now
        shell = MdCLI()
        mdcli.main(argv=[], loop=cmdln.LOOP_ALWAYS)
        

if __name__ == "__main__":
    mdcli = MdCLI()
    sys.exit(mdcli.main())

# End
